// app/(pages)/consultation/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { Form } from '../../../components/Form'
import { officeOptions, timeOptions } from '../../../lib/Options'
import cn from 'classnames'
import { useMobileOrTablet } from '@/lib/useDevice'
import { Montserrat } from 'next/font/google'
import { directus } from '@/lib/directus'
import { createItem } from '@directus/sdk'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['600'],
})

export default function AppointmentSection() {
  const [step, setStep] = useState(1)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isSubmitted, setIsSubmitted] = useState(false)
  const isMobileOrTablet = useMobileOrTablet()

  const [formData, setFormData] = useState({
    office: '',
    service: '',
    time: '',
    firstName: '',
    lastName: '',
    email: '',
    contact: '',
    HearAboutUs: '',
    missingTeeth: '',
    gumDisease: '',
    implants: '',
    dentures: '',
    allowTexting: false,
  })

  const LOCAL_STORAGE_KEY = 'consultationFormData'

  useEffect(() => {
    const savedData = localStorage.getItem(LOCAL_STORAGE_KEY)
    if (savedData) setFormData(JSON.parse(savedData))
  }, [])

  const handleChange = (field: keyof typeof formData) => (value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  const handleCheckboxChange = (checked: boolean) => {
    setFormData((prev) => ({
      ...prev,
      allowTexting: checked,
    }))
  }

  const validateEmail = (email: string) =>
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)

  const validatePhone = (phone: string) => {
    const digitsOnly = phone.replace(/\D/g, '')
    return digitsOnly.length >= 10 && digitsOnly.length <= 15
  }

  const handleNext = () => {
    const fieldErrors: Record<string, string> = {}
    const requiredFields =
      step === 1
        ? ['office', 'time', 'firstName', 'lastName', 'email', 'contact']
        : step === 2
        ? ['missingTeeth', 'gumDisease', 'implants', 'dentures']
        : []

    requiredFields.forEach((key) => {
      const value = formData[key as keyof typeof formData]
      if (typeof value === 'string' && !value.trim()) {
        fieldErrors[key] = 'This field is required!'
      }
    })

    if (step === 1) {
      if (formData.firstName.trim() === '') {
        fieldErrors.firstName = 'First Name is required'
      } else if (!/^[a-zA-Z\s\-']+$/.test(formData.firstName.trim())) {
        fieldErrors.firstName =
          'First Name can only contain letters, spaces, hyphens, and apostrophes'
      } else if (formData.firstName.trim().length > 50) {
        fieldErrors.firstName = 'First Name cannot exceed 50 characters'
      }

      if (formData.lastName.trim() === '') {
        fieldErrors.lastName = 'Last Name is required'
      } else if (!/^[a-zA-Z\s\-']+$/.test(formData.lastName.trim())) {
        fieldErrors.lastName =
          'Last Name can only contain letters, spaces, hyphens, and apostrophes'
      } else if (formData.lastName.trim().length < 2) {
        fieldErrors.lastName = 'Last Name must be at least 2 characters long'
      } else if (formData.lastName.trim().length > 50) {
        fieldErrors.lastName = 'Last Name cannot exceed 50 characters'
      }

      if (!validateEmail(formData.email.trim())) {
        fieldErrors.email = 'Please enter a valid email address'
      }

      if (!validatePhone(formData.contact.trim())) {
        fieldErrors.contact = 'Please enter a valid phone number (10-15 digits)'
      }
    }

    if (Object.keys(fieldErrors).length > 0) {
      setErrors(fieldErrors)
      return
    }

    setErrors({})
    setStep((prev) => prev + 1)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (step !== 2) return

    setIsSubmitting(true)

    try {
      const payload = {
        first_name: formData.firstName,
        last_name: formData.lastName,
        email: formData.email,
        phone: formData.contact,
        allow_texts: formData.allowTexting,
        submission_data: {
          office: formData.office,
          service: formData.service,
          time: formData.time,
          missing_teeth: formData.missingTeeth,
          gum_disease: formData.gumDisease,
          implants: formData.implants,
          dentures: formData.dentures,
          allow_texting: formData.allowTexting,
        },
      }

      await directus.request(createItem('vue_forms', payload))
      localStorage.removeItem(LOCAL_STORAGE_KEY)
      setIsSubmitted(true)
    } catch (err) {
      console.error('Error submitting form:', err)
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleResetForm = () => {
    setFormData({
      office: '',
      service: '',
      time: '',
      firstName: '',
      lastName: '',
      email: '',
      contact: '',
      HearAboutUs: '',
      missingTeeth: '',
      gumDisease: '',
      implants: '',
      dentures: '',
      allowTexting: false,
    })
    setErrors({})
    setIsSubmitted(false)
    setStep(1)
  }

  return (
    <section className="w-full lg:px-8 pt-35 lg:pt-50 pb-15 px-10">
      <div className="max-w-2xl mx-auto text-center">
        <h1
          className={cn(
            `font-bold text-foreground uppercase ${montserrat.className}`,
            isMobileOrTablet
              ? 'text-4xl pt-5 pb-2'
              : 'text-5xl pb-4 whitespace-nowrap'
          )}
        >
          Request a Consultation
        </h1>
        <p className="text-foreground text-sm mb-8">
          Your free screening visit at our New York, New Jersey or Long Island
          offices will include the following: an oral exam, cancer screening,
          dental implant evaluation, your possible treatment options, and
          estimated costs.
        </p>
      </div>

      {isSubmitted ? (
        <div className="max-w-2xl mx-auto text-center py-10">
          <h2 className="text-2xl font-semibold default-blue">
            Thank you! Your consultation request has been submitted.
          </h2>
          <p className="mt-4 text-gray-600">
            Our team will reach out to you soon to confirm your appointment.
          </p>

          <button type="button" onClick={handleResetForm} className="btn mt-8">
            Submit Another
          </button>
        </div>
      ) : (
        <form className="max-w-2xl mx-auto space-y-6" onSubmit={handleSubmit}>
          {step === 1 && (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Form
                  id="firstName"
                  question="First Name"
                  value={formData.firstName}
                  placeholder="Enter Your First Name"
                  onChange={handleChange('firstName')}
                  error={errors.firstName}
                  type="text"
                  required
                />
                <Form
                  id="lastName"
                  question="Last Name"
                  value={formData.lastName}
                  placeholder="Enter Your Last Name"
                  onChange={handleChange('lastName')}
                  error={errors.lastName}
                  type="text"
                  required
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Form
                  id="email"
                  question="Email"
                  required
                  type="email"
                  value={formData.email}
                  onChange={handleChange('email')}
                  placeholder="Email Address"
                  error={errors.email}
                />
                <Form
                  id="contact"
                  question="Phone"
                  required
                  type="text"
                  placeholder="Phone Number"
                  value={formData.contact}
                  onChange={handleChange('contact')}
                  error={errors.contact}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Form
                  id="office"
                  question="Choose Your Location"
                  value={formData.office}
                  onChange={handleChange('office')}
                  error={errors.office}
                  type="select"
                  required
                  options={officeOptions}
                />
                <Form
                  id="time"
                  question="Contact Time"
                  value={formData.time}
                  onChange={handleChange('time')}
                  error={errors.time}
                  type="select"
                  required
                  options={timeOptions}
                />
              </div>

              <div className="flex items-start gap-2 mt-4">
                <Form
                  id="allowTexting"
                  question="By giving your number you agree to receive texts from Advanced Periodontics & Implants. Message frequency varies. Msg & data rates may apply. Reply HELP for help or STOP to opt-out."
                  type="checkbox"
                  value={formData.allowTexting ? 'true' : 'false'}
                  onChange={(val) => handleCheckboxChange(val === 'true')}
                />
              </div>
            </>
          )}

          {step === 2 && (
            <>
              <Form
                id="missingTeeth"
                question="1. Are you missing teeth?"
                value={formData.missingTeeth}
                onChange={handleChange('missingTeeth')}
                error={errors.missingTeeth}
                type="radio"
                required
                options={[
                  { value: 'No Missing', label: 'None' },
                  { value: 'One', label: 'One' },
                  { value: 'Two', label: 'Two' },
                  { value: 'Three+', label: 'Three+' },
                ]}
              />
              <Form
                id="gumDisease"
                question="2. Do you have Gum Disease?"
                value={formData.gumDisease}
                onChange={handleChange('gumDisease')}
                error={errors.gumDisease}
                type="radio"
                required
                options={[
                  { value: 'No Gum Disease', label: 'None' },
                  { value: 'Mild', label: 'Mild' },
                  { value: 'Severe', label: 'Severe' },
                ]}
              />
              <Form
                id="implants"
                question="3. Do you have any previous dental implants?"
                value={formData.implants}
                onChange={handleChange('implants')}
                error={errors.implants}
                type="radio"
                required
                options={[
                  { value: 'Yes', label: 'Yes' },
                  { value: 'No', label: 'No' },
                ]}
              />
              <Form
                id="dentures"
                question="4. Do you currently wear dentures?"
                value={formData.dentures}
                onChange={handleChange('dentures')}
                error={errors.dentures}
                type="radio"
                required
                options={[
                  { value: 'Yes', label: 'Yes' },
                  { value: 'No', label: 'No' },
                ]}
              />
            </>
          )}

          <div
            className={`flex gap-4 ${
              step > 1 ? 'justify-between' : 'justify-end'
            }`}
          >
            {step > 1 && (
              <button
                type="button"
                className="btn"
                onClick={() => setStep((prev) => prev - 1)}
              >
                Previous
              </button>
            )}
            {step < 2 && (
              <button type="button" className="btn" onClick={handleNext}>
                Next
              </button>
            )}
            {step === 2 && (
              <button type="submit" className="btn" disabled={isSubmitting}>
                {isSubmitting ? 'Submitting...' : 'Submit'}
              </button>
            )}
          </div>
        </form>
      )}
    </section>
  )
}

// src/sections/consultation/Consultation.vue
<script setup>
import { ref, reactive, onMounted } from 'vue'
import Input from '../../props/Input.vue'
import { officeOptions, timeOptions } from '../../lib/Options'
import { createDirectus, rest, staticToken, createItem } from '@directus/sdk'
import PageHeader from '../../components/PageHeader.vue'
import SectionFooter from '../../components/SectionFooter.vue'

// --- State ---
const step = ref(1)
const errors = reactive({})
const loading = ref(false)
const submitted = ref(false)

const formData = reactive({
    office: '',
    service: '',
    time: '',
    firstName: '',
    lastName: '',
    email: '',
    contact: '',
    HearAboutUs: '',
    missingTeeth: '',
    gumDisease: '',
    implants: '',
    dentures: '',
    allowTexts: false,
})

// --- Tracking fields ---
const utmSource = ref('')
const utmMedium = ref('')
const utmCampaign = ref('')
const utmTerm = ref('')
const utmContent = ref('')
const pageUrl = ref(window.location.href)
const gclid = ref('')
const fbclid = ref('')

// --- Directus client ---
const clientDirectus = createDirectus(import.meta.env.VITE_DIRECTUS)
    .with(staticToken(import.meta.env.VITE_DIRECTUS_STATIC_TOKEN))
    .with(rest({ credentials: 'include' }))

const LOCAL_STORAGE_KEY = 'consultationFormData'

// --- Tracking helpers ---
function getUrlParameter(name) {
    const urlParams = new URLSearchParams(window.location.search)
    return urlParams.get(name) || ''
}

function saveUtmDataToStorage() {
    const utmData = {
        utm_source: getUrlParameter('utm_source'),
        utm_medium: getUrlParameter('utm_medium'),
        utm_campaign: getUrlParameter('utm_campaign'),
        utm_term: getUrlParameter('utm_term'),
        utm_content: getUrlParameter('utm_content'),
    }

    const gclid1 = getUrlParameter('gclid') || getUrlParameter('cid')
    const fbclid1 = getUrlParameter('fbclid') || getUrlParameter('fbc')

    const hasUtmData = Object.values(utmData).some(
        (v) => v && typeof v === 'string' && v.trim() !== ''
    )

    if (hasUtmData) {
        try {
            localStorage.setItem('utm_tracking_data', JSON.stringify(utmData))
        } catch (err) {
            console.warn('Failed to save UTM data:', err)
        }
    }

    let sixMonths = 60 * 60 * 24 * 30 * 6
    if (gclid1) document.cookie = `gclid=${gclid1};path=/;max-age=${sixMonths}`
    if (fbclid1) document.cookie = `fbclid=${fbclid1};path=/;max-age=${sixMonths}`
}

function getUtmDataFromStorage() {
    try {
        const stored = localStorage.getItem('utm_tracking_data')
        return stored ? JSON.parse(stored) : null
    } catch {
        return null
    }
}

function initializeTrackingFields() {
    const urlUtmSource = getUrlParameter('utm_source')
    const urlUtmMedium = getUrlParameter('utm_medium')
    const urlUtmCampaign = getUrlParameter('utm_campaign')
    const urlUtmTerm = getUrlParameter('utm_term')
    const urlUtmContent = getUrlParameter('utm_content')
    const urlGclid = getUrlParameter('gclid') || getUrlParameter('cid')
    const urlFbclid = getUrlParameter('fbclid') || getUrlParameter('fbc')

    if (
        urlUtmSource ||
        urlUtmMedium ||
        urlUtmCampaign ||
        urlUtmTerm ||
        urlUtmContent ||
        urlGclid ||
        urlFbclid
    ) {
        saveUtmDataToStorage()
        utmSource.value = urlUtmSource
        utmMedium.value = urlUtmMedium
        utmCampaign.value = urlUtmCampaign
        utmTerm.value = urlUtmTerm
        utmContent.value = urlUtmContent
        gclid.value = urlGclid
        fbclid.value = urlFbclid
    } else {
        const stored = getUtmDataFromStorage()
        if (stored) {
            utmSource.value = stored.utm_source || ''
            utmMedium.value = stored.utm_medium || ''
            utmCampaign.value = stored.utm_campaign || ''
            utmTerm.value = stored.utm_term || ''
            utmContent.value = stored.utm_content || ''
        }
        const gclidMatch = document.cookie.match(/(^| )gclid=([^;]+)/)
        const fbclidMatch = document.cookie.match(/(^| )fbclid=([^;]+)/)
        gclid.value = gclidMatch ? gclidMatch[2] : ''
        fbclid.value = fbclidMatch ? fbclidMatch[2] : ''
    }

    pageUrl.value = window.location.href
}

// --- Lifecycle ---
onMounted(() => {
    const savedData = localStorage.getItem(LOCAL_STORAGE_KEY)
    if (savedData) Object.assign(formData, JSON.parse(savedData))
    initializeTrackingFields()
})

// --- Form logic ---
function handleChange(field, value) {
    if (field === 'allowTexts') {
        formData.allowTexts = value === 'true'
    } else {
        formData[field] = value
    }
    saveToLocalStorage()
}

function saveToLocalStorage() {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(formData))
}

function validateEmail(email) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

function validatePhone(phone) {
    const digitsOnly = phone.replace(/\D/g, '')
    return digitsOnly.length >= 10 && digitsOnly.length <= 15
}

function handleNext() {
    const requiredFields =
        step.value === 1
            ? ['firstName', 'lastName', 'email', 'contact', 'office', 'time']
            : step.value === 2
                ? ['missingTeeth', 'gumDisease', 'implants', 'dentures']
                : []

    Object.keys(errors).forEach((key) => delete errors[key])
    let fieldErrors = {}

    requiredFields.forEach((key) => {
        const value = formData[key]
        if (typeof value === 'string' && !value.trim()) {
            fieldErrors[key] = 'This field is required!'
        }
    })

    if (step.value === 1) {
        if (!validateEmail(formData.email.trim())) {
            fieldErrors.email = 'Please enter a valid email address!'
        }
        if (!validatePhone(formData.contact.trim())) {
            fieldErrors.contact = 'Please enter a valid phone number!'
        }
    }

    if (Object.keys(fieldErrors).length > 0) {
        Object.assign(errors, fieldErrors)
        return
    }

    Object.keys(errors).forEach((key) => delete errors[key])
    step.value++
    saveToLocalStorage()
}

async function handleSubmit() {
    if (step.value !== 2) return
    loading.value = true
    try {
        const payload = {
            first_name: formData.firstName,
            last_name: formData.lastName,
            email: formData.email,
            phone: formData.contact,
            allow_texts: formData.allowTexts,
            submission_data: {
                office: formData.office,
                service: formData.service,
                time: formData.time,
                missing_teeth: formData.missingTeeth,
                gum_disease: formData.gumDisease,
                implants: formData.implants,
                dentures: formData.dentures,
                hear_about_us: formData.HearAboutUs,
            },
            utm_source: utmSource.value,
            utm_medium: utmMedium.value,
            utm_campaign: utmCampaign.value,
            utm_term: utmTerm.value,
            utm_content: utmContent.value,
            page_url: pageUrl.value,
            gclid: gclid.value,
            fbclid: fbclid.value,
        }

        await clientDirectus.request(createItem('vue_forms', payload))

        localStorage.removeItem(LOCAL_STORAGE_KEY)
        submitted.value = true
    } catch (err) {
        console.error('Error submitting form:', err)
    } finally {
        loading.value = false
    }
}

function resetForm() {
    step.value = 1
    submitted.value = false
    Object.keys(errors).forEach((key) => delete errors[key])
    for (const key in formData) {
        formData[key] = key === 'allowTexts' ? false : ''
    }
}
</script>

<template>
    <section class="min-h-screen flex flex-col bg-white">
        <PageHeader />
        <div class="md:h-16 h-28"></div>

        <div class="flex flex-col px-6 mx-auto max-w-[1160px] container py-10">
            <div class="mx-auto text-center">
                <h1 class="text-3xl uppercase md:text-[40px] text-center w-full default-gray headingFont">
                    Request a Consultation
                </h1>
                <p class="text-foreground text-sm mb-8">
                    Your free screening visit at our New York, New Jersey or Long Island offices will include the
                    following:
                    an oral exam, cancer screening, dental implant evaluation, your possible treatment options, and
                    estimated costs.
                </p>
                <hr className="my-1 w-full border-t border-gray-400 pb-4" />
            </div>

            <!-- Thank you state -->
            <div v-if="submitted" class="text-center py-14">
                <h2 class="text-2xl font-semibold default-blue montserrat uppercase">
                    Thank you! Your consultation request has been submitted.
                </h2>
                <p class="mt-1 text-foreground">
                    Our team will reach out to you soon to confirm your appointment.
                </p>
                <button type="button" @click="resetForm" class="btn mt-1">
                    Submit Another
                </button>
            </div>

            <!-- Form state -->
            <form v-else class="space-y-6 px-4" @submit.prevent="handleSubmit">
                <!-- Step 1 -->
                <template v-if="step === 1">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Input id="firstName" question="First Name" type="text" placeholder="Enter Your First Name"
                            :value="formData.firstName" :error="errors.firstName"
                            @update="handleChange('firstName', $event)" required />
                        <Input id="lastName" question="Last Name" type="text" placeholder="Enter Your Last Name"
                            :value="formData.lastName" :error="errors.lastName"
                            @update="handleChange('lastName', $event)" required />
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Input id="email" question="Email" type="email" placeholder="Email Address"
                            :value="formData.email" :error="errors.email" @update="handleChange('email', $event)"
                            required />
                        <Input id="contact" question="Phone" type="text" placeholder="Phone Number"
                            :value="formData.contact" :error="errors.contact" @update="handleChange('contact', $event)"
                            required />
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Input id="office" question="Choose Your Location" type="select" :value="formData.office"
                            :options="officeOptions" :error="errors.office" @update="handleChange('office', $event)"
                            required />
                        <Input id="time" question="Contact Time" type="select" :value="formData.time"
                            :options="timeOptions" :error="errors.time" @update="handleChange('time', $event)"
                            required />
                    </div>

                    <div class="flex items-start gap-2 mt-4">
                        <Input id="allowTexts" type="checkbox"
                            question="By giving your number you agree to receive texts from Advanced Periodontics & Implants. Message frequency varies. Msg & data rates may apply. Reply HELP for help or STOP to opt-out."
                            :value="formData.allowTexts ? 'true' : 'false'" :error="errors.allowTexts"
                            @update="handleChange('allowTexts', $event)" />
                    </div>
                </template>

                <!-- Step 2 -->
                <template v-if="step === 2">
                    <Input id="missingTeeth" question="1. Are you missing teeth?" type="radio"
                        :value="formData.missingTeeth" :error="errors.missingTeeth" :options="[
                            { value: 'No Missing', label: 'None' },
                            { value: 'One', label: 'One' },
                            { value: 'Two', label: 'Two' },
                            { value: 'Three+', label: 'Three+' }
                        ]" @update="handleChange('missingTeeth', $event)" required />

                    <Input id="gumDisease" question="2. Do you have Gum Disease?" type="radio"
                        :value="formData.gumDisease" :error="errors.gumDisease" :options="[
                            { value: 'No Gum Disease', label: 'None' },
                            { value: 'Mild', label: 'Mild' },
                            { value: 'Severe', label: 'Severe' }
                        ]" @update="handleChange('gumDisease', $event)" required />

                    <Input id="implants" question="3. Do you have any previous dental implants?" type="radio"
                        :value="formData.implants" :error="errors.implants" :options="[
                            { value: 'Yes', label: 'Yes' },
                            { value: 'No', label: 'No' }
                        ]" @update="handleChange('implants', $event)" required />

                    <Input id="dentures" question="4. Do you currently wear dentures?" type="radio"
                        :value="formData.dentures" :error="errors.dentures" :options="[
                            { value: 'Yes', label: 'Yes' },
                            { value: 'No', label: 'No' }
                        ]" @update="handleChange('dentures', $event)" required />
                </template>

                <!-- Buttons -->
                <div class="flex gap-4" :class="step > 1 ? 'justify-between' : 'justify-end'">
                    <button v-if="step > 1" type="button" class="btn" @click="step--">Previous</button>
                    <button v-if="step < 2" type="button" class="btn" @click="handleNext">Next</button>
                    <button v-if="step === 2" type="submit" class="btn" :disabled="loading">
                        {{ loading ? 'Submitting...' : 'Submit' }}
                    </button>
                </div>
            </form>
        </div>
        <SectionFooter />
    </section>

</template>

<style scoped></style>
